### ISSUE TITLE
[Request] Time on map

### ISSUE THREAD

**Issue by api-h** [ucl-team-8/service#28]
Is there a way we can get a time running on the visualisation, so we know what time it is in the simulation?

**Comment by AxelGoetz** [comment]
This is possible, but it will never be very accurate because I can think of 2 ways of doing it:
1. If a client connects, they request the time of the last report that has been processed and the speedup factor. Then they 'simulate' their own time. But the problem here is that if the speedup factor is too high (>1000), this can get very inaccurate because the threadpool cannot keep up with the rate that reports are coming in.
2. The client updates the current time, whenever it receives a segment through a socket. This will be slightly more accurate, but then again if there is a 10-minute delay between 1 report and the next, it will take a while for the time to be updated.

**Comment by api-h** [comment]
We'l have to put this one in the nice to have and leave it for now I guess

**Comment by AxelGoetz** [comment]
Fixed in 7e387190b51c1f2198468b53cd07b7c53b2946f3
